
<?php $title = 'Blog Billet simple pour l\'Alaska'; ?>

<?php ob_start(); ?>

    <h1>Bienvenue sur l'interface administrateur</h1>

    <h2><p>Je me connecte</p></h2>

    <form action='index2.php?action=verifyController' method='POST'>

    <p><label><strong>Identifiant</strong></label><input type="action" name="login"></p>
    <p><label><strong>Mot de passe</strong></label><input type="password" name="pass"></p>
    <p><input type="submit" value="Valider"></p>

    </form>

<?php $content = ob_get_clean(); ?>

<?php require('view/template.php'); ?>


<p><a href ="index2.php"> Retour à la liste des chapitres </a></p>
  