
<?php $title = 'Blog Billet simple pour l\'Alaska'; ?>


    <h1>Billet simple pour l'Alaska</h1>


    <p><a href ="index.php"> Retour à la liste des chapitres </a></p>

    <?php

    while ($data=$chapters-> fetch())
    {
    ?>

    <table class="chapters"/>
    <tr>
        <td>
        <?php echo $data['title'] ?>
        </td>
        <td>
        le <?= $data['creation_date_fr'] ?>
        </td>
    

        <td>
        <form action="index.php?action=editChapter&amp;id=<?= $data['id'] ?>" method="POST"/>
        <input type="submit" value="Modifier"/>
        </form></td>

        <td><form action="index.php?action=removeChapter&amp;id=<?= $data['id'] ?>" method="POST"/>
        <input type="submit" name="Supprimer" value="Supprimer" id="button"/>
        </form></td>
    </tr>
    </table>

    <?php
    }
    $chapters->closeCursor();
    ?>

    <h2 class="ajout"> Ajouter un nouveau chapitre </h2>




    <form action='index.php?action=addChapter' method='post'>
        
    <div>
        <label for="title">Titre chapitre</label><br />
        <textarea id="title" name="title"></textarea>
    </div>
    <div>
        <label for="content">Texte</label><br />
        <textarea id="#mytextarea" name="content"></textarea>
    </div>
    <div>
        <input type="submit" />
    </div>
    </form>

    <h3 class="commentlist"> Les derniers commentaire</h3>
    

    <?php    

    while ($dat=$listcomments-> fetch())
    {
    ?>

    <div class="news"/>
    <h4>
    <?php echo $dat['author'] ?>
    le <?= $dat['creation_date_fr'] ?>
    </h4>

    <p>
       
    <?php

    $res=$dat['content'];
    
    echo $res; ?><br/>
    <?
    if ($dat['signaled'] == 1)
        {
            echo 'Ce commentaire a été signalé';?>
        <form action="index.php?action=removeComment&amp;id=<?= $dat['id'] ?>" method="POST"/>
        <input type="submit" name="SupprimerCommentaires" value="Supprimer" />
        </form>
        <?}

    ?>
       
    </p>
    </div>


<?php
}
$chapters->closeCursor();?>

<foot>
    <a href="index.php?action=deconnexion"> Deconnexion </a>
</foot>