
<?php $title='Blog Billet simple pour l\'Alaska'; ?>

    
<?php

$req= new FlashMessageSession();

$flash = $req->asMessage();
var_dump($flash);
if ($flash==true)
{?> 
    <div class="alert alert-success alert-dismissable col-lg-12">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <? $set = $req->showFlash();?> 
    </div> 
<?}
?>
    
<div class="container">
    <header class="page-header">
        <h1>Billet simple pour l'Alaska</h1>
    </header>
    <section class="row">
<div class="col-sm-12">


<p><a href ="index.php"> Retour à la liste des chapitres </a></p>

	<div class="row">

        <section class="col-sm-offset-2 col-sm-8">

    	   <h3>
    	       <?php echo $chapter['title'] ?>
    	       <em>le <?php echo $chapter['creation_date_fr'] ?></em>
    	   </h3>

    	   <p><?php echo $chapter['content'] ?></p>
        </section>
    </div>

	<?php

        while ($data=$comments-> fetch())
   
        {
        ?>
        <div class="news"/>
            <h4>
            <?php echo $data['author'] ?>
            le <?= $data['creation_date_fr'] ?>
            </h4>

        <p><?php echo $data['content']?></p>
        </div>


        <form action="index.php?action=signaledComment&amp;id=<?= $data['id'] ?>" method='post'>
            <input type="hidden" name="id" value="<?=$chapter['id']?>"/> 
        <button class="btn btn-xs btn-warning" type="submit"><span class="glyphicon glyphicon-warning-sign"></span> Signaler</button>
        </form>
       
        <?php
		}
		$comments->closeCursor();
		?>

            <h5> Ajouter un nouveau commentaire </h5>

        <form action="index.php?action=addComment&amp;id=<?= $data['id'] ?>" method='post'>

    	   <input type="hidden" name="id" value="<?=$chapter['id']?>"/>    
        
            <div>
                <label for="author">Votre pseudo</label><br />
                <input type="text" id="author" name="author">
            </div>
            <div>
                <label for="content">Texte</label><br />
                <textarea id="content" name="content"></textarea>
            </div>
            <div>
                <button class="btn btn-primary btn-success"><span class="glyphicon glyphicon-chevron-down"></span> Envoyer</button>
            </div>
        </form>

        <section class="col-sm-12">  
        <footer>
            <?php
            $connected= new UserSession();
            $logged=$connected->isLogged();
            if ($logged==TRUE)
            { ?>
                <div class="col-sm-3">
                <a class="admin" href="index.php?action=deconnexion"> Deconnexion </a>
                </div>
                <div class="col-sm-offset-7 col-sm-2">
                <a class="admin" href="index.php?action=showAdmin"> Page admin </a>
                </div>
                
            <?php }
            $connected= new UserSession();
            $logged=$connected->isLogged();
            if ($logged==FALSE)
            { ?>
                <a class="admin" href="index.php?action=connexion"> Connexion admin du site </a>
                
            <?php }
            ?>
        </footer>
        </section>
    </div>
        </section>
    </div>

