
<?php $title='Blog Billet simple pour l\'Alaska'; ?>

 <?php
        
        $req= new FlashMessageSession();
        $flash = $req->asMessage();
        ?>


<h1>Billet simple pour l'Alaska</h1>




	<p><a href ="index.php"> Retour à la liste des chapitres </a></p>

	<div class="news">

	<h3>
	<?php echo $chapter['title'] ?>
	<em>le <?php echo $chapter['creation_date_fr'] ?></em>
	</h3>

	<p><?php echo $chapter['content'] ?></p>

	<?php

while ($data=$comments-> fetch())
   
{
?>
    <div class="news"/>
    <h4>
    <?php echo $data['author'] ?>
    le <?= $data['creation_date_fr'] ?>
    </h4>

    <p><?php echo $data['content']?></p>


        <form action="index.php?action=signaledComment&amp;id=<?= $data['id'] ?>" method='post'>
            <input type="hidden" name="id" value="<?=$chapter['id']?>"/> 
        <button class="btn btn-xs btn-warning" type="submit"><span class="glyphicon glyphicon-warning-sign"></span> Signaler</button>
        </form>
       
        <?php
		}
		$comments->closeCursor();
		?>

<h5> Ajouter un nouveau commentaire </h5>

    <form action="index.php?action=addComment&amp;id=<?= $data['id'] ?>" method='post'>

    	<input type="hidden" name="id" value="<?=$chapter['id']?>"/>    
        
    <div>
        <label for="author">Votre pseudo</label><br />
        <textarea id="author" name="author"></textarea>
    </div>
    <div>
        <label for="content">Texte</label><br />
        <textarea id="content" name="content"></textarea>
    </div>
    <div>
        <button class="btn btn-primary btn-success"><span class="glyphicon glyphicon-chevron-down"></span> Envoyer</a>
    </div>
    </form>

