
<?php $title = 'Blog Billet simple pour l\'Alaska'; ?>

	<div class="container2">
      	<header>
	        <div class="col-sm-12 col-lg-10">
	    		<h1>Bienvenue sur l'interface administrateur</h1>
	    	</div>
	    </header>
	    	<br><br>
	    	<div class="col-sm-12 col-lg-10">
    			<h2><p>Je me connecte</p></h2>
    		</div>
   		<section>
        	<div class="col-lg-12">
    			<form action='index.php?action=verifyController' method='POST'>

    			<p><label><strong>Identifiant</strong></label><input type="action" name="login"></p>
    			<p><label><strong>Mot de passe</strong></label><input type="password" name="pass"></p>
    			<button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-ok-sign"></span> Envoyer</button>

    			</form>
    		</div>
    	</section>
    </div>


<p><a href ="index.php"> Retour à la liste des chapitres </a></p>
  