
<?php $title = 'Blog Billet simple pour l\'Alaska'; ?>

<?php ob_start(); ?>

<h1>Billet simple pour l'Alaska</h1>



    <p><a href ="index2.php?action=showAdmin"> Retour à la liste des chapitres </a></p>

    <div class="news">

    <h3>
    
    <em>le <?=htmlspecialchars($chapter['creation_date_fr']) ?></em>
    </h3>

    
    </div>


    <h4> Modifier le chapitre </h4>

    <form action='index2.php?action=editChapter' method='post'>
    
    <input type="hidden" name="id" value="<?=htmlspecialchars($chapter['id'])?>"/>  
    <?php var_dump($chapter);?>
    <div>
        <label for="newtitle">Titre chapitre</label><br />
        <textarea id="newtitle" name="newtitle"><?= htmlspecialchars($chapter['title']) ?></textarea>

    </div>
    <div>
        <label for="newcontent">Texte</label><br />
        <textarea id="newcontent" name="newcontent" ><?= nl2br(htmlspecialchars($chapter['content'])) ?></textarea>
    </div>
    <div>
        <input type="submit" />
    </div>
    </form>

<?php $content = ob_get_clean(); ?>

<?php require('view/template.php'); ?>

<footer>
    <a href="index2.php?action=deconnexion"> Deconnexion</a>
</footer>