
<?php $title = 'Blog Billet simple pour l\'Alaska'; ?>

<?php
        
$req= new FlashMessageSession();
$flash = $req->asMessage();
?> 


<h1>Billet simple pour l'Alaska</h1>



    <p><a href ="index.php?action=showAdmin"> Retour à la liste des chapitres </a></p>

    <div class="news">

    <h3>
    
    <em>le <?php echo $chapter['creation_date_fr'] ?></em>
    </h3>

    
    </div>


    <h4> Modifier le chapitre </h4>

    <form action='index.php?action=editChapter' method='post'>
    
    <input type="hidden" name="id" value="<?php echo $chapter['id']?>"/>  
    
    <div>
        <label for="newtitle">Titre chapitre</label><br />
        <textarea id="newtitle" name="newtitle"><?php echo $chapter['title'] ?></textarea>

    </div>
    <div>
        <label for="newcontent">Texte</label><br />
        <textarea id="newcontent" name="newcontent" ><?php echo $chapter['content'] ?></textarea>
    </div>
    <div>
        <input type="submit" />
    </div>
    </form>

<footer>
    <a href="index.php?action=deconnexion"> Deconnexion</a>
</footer>