<?php
if ($flash==true)
{?> 
    <div class="alert alert-success alert-dismissable col-lg-12">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <?php 
    $set = $req->showFlash();
    ?>  
    </div> 
<?php }
?>

<body>
    <div class="container">
        <header class="page-header">
            <h1>Billet simple pour l'Alaska</h1>
        </header>

        <div class="col-sm-12">


        <section class="col-sm-12"> 
            <p><a href ="index.php?action=showAdmin"> Retour à la liste des chapitres </a></p>

            <h3>
            <em>le <?php echo $chapter['creation_date_fr'] ?></em>
            </h3>

            <h4> Modifier le chapitre </h4>

            <form action='index.php?action=editChapter' method='post'>
            
            <input type="hidden" name="id" value="<?php echo $chapter['id']?>"/>  
            
            <div>
                <label for="newtitle">Titre chapitre</label><br />
                <input type="text" id="newtitle" name="newtitle" value="<?php echo $chapter['title'] ?>"/>

            </div>

            <div>
                <label for="newcontent">Texte</label><br />
                <textarea id="newcontent" name="newcontent" ><?php echo $chapter['content'] ?></textarea>
            </div>

            <div>
                <button class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-floppy-saved"></span> Enregistrer</button>
            </div>
            </form>
        </section>
        </div>

    </div>
</body>