<?php $title='Blog Billet simple pour l\'Alaska'; ?>


<?php ob_start(); ?> 

<h1>Billet simple pour l'Alaska</h1>


<h2>Le blog de Jean Forteroche</h2>



<a href="Forterocheportrait.jpeg"/><img class="portrait" src="Forterocheportrait_mini.jpeg" alt="portrait photo"/></a>

<h3>A propos de l'autheur</h3>
<p> Jean Forteroche né le 18 juillet 1965, est né à Annecy, il y vit toujours et trouve son inspiration par sa région.Romancier, il est également scénariste et a coécrit, avec Nicolas Tackian, les dialogues du film de Pierre Isoard intitulé Alex Hugo, la mort et la belle vie : film inspiré d'un roman américain, relocalisé en Provence pour l'adaptation à la télévision.
Grand passionné de thriller à l'instar de 8 millimètres de Joel Schumacher, on en retrouve quelques clins d'œil dans ses romans.
Jean Forteroche est membre du collectif d'artistes La Ligue de l'Imaginaire.</p>



<h4>Principe du Blog</h4>
<p> Jean Forteroche toujours à l'affût de nouvelles formes de communications et d'expression, a choisi de faire un cadeau a ses fans et de publier chaque semaine un chapitre de son nouveau roman "Billet simple pour l'Alaska": Il reste très à l'écoute de ses lecteurs et donne donc la possibilité de publier des commentaires sur chacun de ses chapitres.</p>

<p>Derniers billets du blog :</p>

<?php

while ($data=$chapters-> fetch())
   
{
?>
    <div class="news"/>
    <h5>
    <?= htmlspecialchars($data['title']) ?>
    le <?= $data['creation_date_fr'] ?>
    </h4>

    <p>
       
        <?php

        $res=$data['content'];
        $res=substr($res, 0, 30);
        echo $res;

        ?>
        <br />
        <em><a href="index2.php?action=chapter&amp;id=<?= $data['id'] ?>">Lire la suite...</a></em>
    </p>
    </div>
<?php
}
$chapters->closeCursor();
?>

<?php $content = ob_get_clean(); ?>

<?php require('view/template.php'); ?>
   
<foot>
    <?php
    $connected= new UserSession();
    $logged=$connected->isLogged();
    if ($logged==TRUE)
    { ?>
        <a class="admin" href="index.php?action=deconnexion"> Deconnexion </a>
        
    <?php }
    else
    { ?>
        <a class="admin" href="index.php?action=connexion"> Connexion admin </a>
    <?php }
    ?>
</foot>
