<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
        <script src="bootstrap/js/jquery.js"></script>
        <link href="view/style.css" rel="stylesheet">
        <script src="bootstrap/js/bootstrap.js" rel="stylesheet"></script>
        <script type="text/javascript" src="tinymce/tinymce.js"></script>
        <script type="text/javascript">
        tinyMCE.init({
        	selector : 'textarea',
            
            language : "fr",});
        </script>
        <script src="bootstrap/js/jquery.js"></script>
        <title><?= $title ?></title>
        
    </head>
        
    <body>

        <?php include $template . 'View.phtml'; ?>
    </body>

</html>

