<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <script type="text/javascript" src="tinymce/tinymce.js"></script>
        <script type="text/javascript">
        tinyMCE.init({
        	selector : 'textarea',
            
            language : "fr",});
     </script>
        <title><?= $title ?></title>
        
    </head>
        
    <body>
        <?php include $template . 'View.phtml'; ?>
    </body>
</html>